/******* Do not edit this file *******

This is and Add Blocker test page


Saved: Mar 23 2020 | 10:31:14 */




function docReady(fn) {
    // see if DOM is already available
    if (document.readyState === "complete" || document.readyState === "interactive") {
        // call on next available tick
        setTimeout(fn, 1);
    } else {
        document.addEventListener("DOMContentLoaded", fn);
    }
} 

docReady(function() {
    // DOM is loaded and ready for manipulation here
  	var e = document.createElement('div');
	e.setAttribute("id", "sROfUCrkFhSV");
	e.style.display = "none";
	var body = document.getElementsByTagName("BODY")[0];
	body.appendChild(e);
});