/* Local pack index.js starts here */
/*
 Copyright (c) Tabelaofert Sp. z o.o. (https://tabelaofert.pl)
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,c,b){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(c.call(b,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){if(a==Array.prototype||a==Object.prototype)return a;a[c]=b.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var c=0;c<a.length;++c){var b=a[c];if(b&&b.Math==Math)return b}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,c){var b=$jscomp.propertyToPolyfillSymbol[c];if(null==b)return a[c];b=a[b];return void 0!==b?b:a[c]};
$jscomp.polyfill=function(a,c,b,d){c&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,c,b,d):$jscomp.polyfillUnisolated(a,c,b,d))};$jscomp.polyfillUnisolated=function(a,c,b,d){b=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];if(!(e in b))return;b=b[e]}a=a[a.length-1];d=b[a];c=c(d);c!=d&&null!=c&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:c})};
$jscomp.polyfillIsolated=function(a,c,b,d){var e=a.split(".");a=1===e.length;d=e[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<e.length-1;f++){var g=e[f];if(!(g in d))return;d=d[g]}e=e[e.length-1];b=$jscomp.IS_SYMBOL_NATIVE&&"es6"===b?d[e]:null;c=c(b);null!=c&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:c}):c!==b&&(void 0===$jscomp.propertyToPolyfillSymbol[e]&&(b=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+b+"$"+e),$jscomp.defineProperty(d,$jscomp.propertyToPolyfillSymbol[e],{configurable:!0,writable:!0,value:c})))};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(c,b){return $jscomp.findInternal(this,c,b).v}},"es6","es3");
(function(a){a.widget("to.specjalne",{version:"1",options:{},_create:function(){this._initLinks();this._initCarousel()},_initLinks:function(){this.element.find("a.opis").each(function(c,b){a(b).click(function(d){if(1==a.event.fix(d).which){var e=a(this).closest("a"),f=e.attr("data-tracklink");GA.event("Strona g\u0142\u00f3wna","Oferta specjalna",f);d=e.attr("data-www");if(void 0!=d){f=f.match(/\d+$/)[0];var g=e.attr("data-klient");a.fn.hit("INWESTYCJA-WWWCPC",f);GA.event("CPC","Oferta specjalna g\u0142\u00f3wna",
"Klient/"+g+"/Inwestycja/"+f);window.open(d,g);window.setTimeout(function(){window.location=e.attr("href")},750);return!1}}})})},_initCarousel:function(){var c=this.element.find(".slide");c.hide();var b=null,d=1,e=0,f=function(k){a(c[e%c.length]).fadeOut(800);a(c[e%c.length]).removeClass("active");a(c[k%c.length]).fadeIn(800);a(c[k%c.length]).addClass("active");e=k},g=function(){f(d++)};if(1<c.length){var h=setInterval(g,6E3);this.element.find(".prev").click(function(){clearTimeout(b);clearInterval(h);
d--;0>d&&(d+=c.length);b=setTimeout(function(){f(d);h=setInterval(g,6E3)},200)});this.element.find(".next").click(function(){clearTimeout(b);clearInterval(h);d++;b=setTimeout(function(){f(d);h=setInterval(g,6E3)},200)})}else this.element.find(".prev,.next").hide();f(e)}})})(jQuery);(function(a){a.widget("to.core",a.to.core,function(){var c;return{_create:function(){c=this;this._super();this._initSpecjalne();this._topmenuGA();this._initEvents()},_initSpecjalne:function(){c.element.find(".ng-specjalna").specjalne()},_topmenuGA:function(){a("#ng_topmenu .info").on("click",function(b){""!=a(this).attr("href")&&(b=a(this).attr("href").split(",").pop(),b=b.replace("i",""),b.match(/^\d+$/)&&GA.event("Strona g\u0142\u00f3wna","Top menu","Inwestycja/"+b))})},_initEvents:function(){a(".box-cta[data-ga]").each(function(){var b=
a(this).data("ga");a.fn.hit("INWESTYCJA-SZUKARKA-ODSLONA",b)});a(".box-cta[data-ga]").click(function(){var b=a(this).data("ga");a.fn.hit("INWESTYCJA-SZUKARKA-KLIKNIECIE",b);GA.event("Strona g\u0142\u00f3wna","Zdj\u0119cie pod szukark\u0105","Inwestycja_click/"+b)})},_dontTouch:null}}())})(jQuery);